name: validate workflows
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Run actionlint
      uses: docker://rhysd/actionlint:latest
      with:
       args: -color
    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
